# NumPy Arrays

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

##### Casting list to an array

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3], [4,5,6]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6]])

##### Similar to range func

In [7]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

##### Linspace returns evenly spaced numbers over a specified interval

In [13]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

##### Creating an identity matrix

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

##### Random - rand : uniform distribution 0 - 1

In [15]:
np.random.rand(5)

array([0.52277602, 0.22034864, 0.92478615, 0.32993621, 0.96307918])

In [18]:
np.random.rand(2,3)

array([[0.36990106, 0.08647383, 0.12408958],
       [0.90765369, 0.47515581, 0.08282195]])

##### Random - randn : standard normal distribution centered around 0

In [19]:
np.random.randn(2)

array([ 0.67451597, -0.17598834])

In [20]:
np.random.randn(4,4)

array([[-0.45513199,  0.03222415,  0.51394952,  0.56918445],
       [ 1.50422731, -1.73507863,  0.9625969 ,  0.42055917],
       [-0.68157359, -1.29138536, -1.04995353, -1.73525345],
       [-0.74664836, -1.2479803 ,  1.26745706,  1.9474697 ]])

##### Random - randint : (low, high, size)

In [22]:
np.random.randint(0,100)

49

In [23]:
np.random.randint(0,100,10)

array([19,  9, 25,  0, 52, 63, 88, 96, 38, 99])

In [24]:
arr = np.arange(25)

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
rand_arr = np.random.randint(0,50,10)

In [27]:
rand_arr

array([46,  7,  2, 40, 36, 47,  8, 33, 40,  5])

In [28]:
rand_arr.max()

47

In [29]:
rand_arr.min()

2

In [30]:
rand_arr.argmax()

5

In [31]:
rand_arr.argmin()

2

In [33]:
arr.shape

(25,)

In [34]:
arr = arr.reshape(5,5)

In [35]:
arr.shape

(5, 5)

In [36]:
arr.dtype

dtype('int64')